<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Tin hnh t hng</name>
   <tag></tag>
   <elementGuidId>31126861-03f5-49b2-9274-635474c50047</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_checkout > span > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_checkout']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>2fd82d7c-16c9-4b04-8672-a0d82d182d4a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Tiến hành đặt hàng</value>
      <webElementGuid>c9a68495-bce6-437a-adaa-a6857d901d50</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_checkout&quot;)/span[1]/span[1]</value>
      <webElementGuid>2bca0fa2-92db-46cc-808f-39e162818db3</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn_checkout']/span/span</value>
      <webElementGuid>d53d52bd-e2eb-46d2-9be8-cc2bc24c8883</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tổng tiền :'])[1]/following::span[2]</value>
      <webElementGuid>f67cd566-2e0a-4cf3-a1f1-dbc679437bf5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tạm tính :'])[1]/following::span[2]</value>
      <webElementGuid>6870ff4e-579b-457f-ad7e-0c220ef93465</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chủ sở hữu'])[1]/preceding::span[1]</value>
      <webElementGuid>066b161d-4e32-448f-a356-e2084890dfe0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Tiến hành đặt hàng']/parent::*</value>
      <webElementGuid>e8514005-5c6b-4f6e-9e57-9cc1e07ecb6a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li/button/span/span</value>
      <webElementGuid>1dbb3f5d-2609-4c71-909c-470a304fd91d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Tiến hành đặt hàng' or . = 'Tiến hành đặt hàng')]</value>
      <webElementGuid>8acaa533-4fe8-4d32-ac7a-e9eb7bf1577f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
