<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_NG K</name>
   <tag></tag>
   <elementGuidId>a56674f6-f00c-42ba-abbb-bcf1fd8ef54f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_register > span > span</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_register']/span/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>c9c25176-369e-430d-8d2b-2074e357f4c7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>ĐĂNG KÝ</value>
      <webElementGuid>5dcbcac0-2d70-4693-bc0d-3b4dfc23e7f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_register&quot;)/span[1]/span[1]</value>
      <webElementGuid>58b9ecec-c7a9-4a27-b5f0-ce9f1ac78b66</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//button[@id='btn_register']/span/span</value>
      <webElementGuid>4057841a-875c-455f-ac63-633e89cc3562</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='điều khoản sử dụng'])[1]/following::span[2]</value>
      <webElementGuid>26e5a50e-220d-4e14-b3b6-5587564562e3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::span[2]</value>
      <webElementGuid>0a11000e-53ae-4dab-a65f-17f3a3f1e7a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chủ sở hữu'])[1]/preceding::span[1]</value>
      <webElementGuid>060fd7b1-78e1-47d7-80c5-23b70ebd0e6b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='ĐĂNG KÝ']/parent::*</value>
      <webElementGuid>1eefce14-9073-440e-a566-b540bea63deb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div/button/span/span</value>
      <webElementGuid>7ee76abb-717d-490b-8686-7830f9a36417</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'ĐĂNG KÝ' or . = 'ĐĂNG KÝ')]</value>
      <webElementGuid>073f0e5a-2c94-4ffa-ae33-4794d2412bdd</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
