<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input__re_password</name>
   <tag></tag>
   <elementGuidId>c1cb18d7-53a9-489a-a714-c4a891d31ef7</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#re_password</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='re_password']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>b67140ff-ff43-4217-b207-164cefe2082d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>password</value>
      <webElementGuid>7babf594-48f6-4b66-9c71-cd69349dfa3b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>re_password</value>
      <webElementGuid>9c93b21e-021d-4493-a404-b3375bf657a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>re_password</value>
      <webElementGuid>bbe14e91-80b2-4222-914f-86555d58ebda</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>0c4c7ab6-86b1-42cb-9049-8384d97a13b9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;re_password&quot;)</value>
      <webElementGuid>694811de-ed63-41cf-88f4-928ae68a043e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='re_password']</value>
      <webElementGuid>70e02b7d-e42d-460d-be58-1c6562f75d89</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[7]/div/input</value>
      <webElementGuid>e9b2cb8f-940e-4274-aad1-11b6bf599fdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@type = 'password' and @id = 're_password' and @name = 're_password']</value>
      <webElementGuid>4173dd24-3bec-4fa8-9197-f713d2f0dd91</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
