<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_demogmail.com</name>
   <tag></tag>
   <elementGuidId>e32ecc96-a382-4ea2-9764-5e1a4e0aad8d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#getAddress</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='getAddress']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>2f9b0c7a-e2ca-4770-9d82-bbba14de50d5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>address</value>
      <webElementGuid>1fc8d216-a552-4bf7-9981-e11502216397</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>b6f647f9-ed77-4914-96df-56b83e3ef7ae</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>getAddress</value>
      <webElementGuid>d2890813-df6f-4fe7-bda4-9101f16c5fbb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>demo@gmail.com</value>
      <webElementGuid>6e2b0ad6-60ab-477b-8be2-07a0e0c7055b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;getAddress&quot;)</value>
      <webElementGuid>01855f76-1a30-44ee-8028-aad7a7b80055</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='getAddress']</value>
      <webElementGuid>c0ee291a-1b8f-45a1-b617-b4ce78d2126f</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='billing-new-address-form']/fieldset/ul/li[3]/div/textarea</value>
      <webElementGuid>f74a184d-215a-47d9-94bb-31d1e26a57af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[3]/following::textarea[1]</value>
      <webElementGuid>71fd3454-4441-4cdd-9084-441c06fd8365</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ghi chú cho đơn hàng (Không bắt buộc)'])[1]/preceding::textarea[1]</value>
      <webElementGuid>f5324043-c8a9-4680-8e2b-bdf35527820c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đặt mua'])[1]/preceding::textarea[2]</value>
      <webElementGuid>4d26d21b-5150-4500-baa8-a0c6646056dd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='demo@gmail.com']/parent::*</value>
      <webElementGuid>0a33c4b7-bbb0-4ac5-9544-4e539c9387ae</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//textarea</value>
      <webElementGuid>599a5864-b4c0-49e2-bf07-dcabd77c89ab</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'address' and @id = 'getAddress' and (text() = 'demo@gmail.com' or . = 'demo@gmail.com')]</value>
      <webElementGuid>2fa8ab0c-2a24-45b9-952a-f233c7f943df</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
