<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>textarea_Ghi ch cho n hng (Khng bt buc)_note</name>
   <tag></tag>
   <elementGuidId>d899da08-9778-4456-af3d-a20790341750</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#getNote</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//textarea[@id='getNote']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>textarea</value>
      <webElementGuid>8e4da708-0d1e-403a-ac30-dcd7e7b376b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>note</value>
      <webElementGuid>d20e4c94-96e4-477e-9507-953cf730dd62</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>form-control</value>
      <webElementGuid>8cbad918-de9c-4367-afc3-347896e307df</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>getNote</value>
      <webElementGuid>70e174d3-1976-4ef3-a033-ca299f872c95</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;getNote&quot;)</value>
      <webElementGuid>2cc6145b-2fe0-4d10-9521-5fd75cfc9f22</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//textarea[@id='getNote']</value>
      <webElementGuid>e4adcc04-a89e-4022-9767-b358ef65bff5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//li[@id='billing-new-address-form']/fieldset/ul/li[4]/div/textarea</value>
      <webElementGuid>9f6c2af1-51ac-4ee3-acda-8d6e1b26480b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//li[4]/div/textarea</value>
      <webElementGuid>4110543f-5063-4b92-bfe3-2ca0cd482777</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//textarea[@name = 'note' and @id = 'getNote']</value>
      <webElementGuid>e4eead20-b957-4adc-bfdd-01690eb4ccb9</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
