<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_ng nhp</name>
   <tag></tag>
   <elementGuidId>3def7652-1ea8-44b1-a506-bf94bfa10a69</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#btn_login</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@id='btn_login']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>6c0577ea-2d7c-42e3-8101-83a80ce69fbe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>ee25efc2-9f4f-45c6-8add-a873cbf6ae7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>btn_login</value>
      <webElementGuid>9d0e7c14-4680-4c2c-a0a5-174ffc2b46fe</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>button btn-login</value>
      <webElementGuid>8004f7a3-be01-4ebc-8172-28c13bb19acb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Đăng nhập
                            </value>
      <webElementGuid>bc1be930-5cbf-480d-b42e-8fb11725a575</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;btn_login&quot;)</value>
      <webElementGuid>a399ad1e-a6dc-476d-8549-6f4b60f62e4d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//button[@id='btn_login']</value>
      <webElementGuid>f035734f-a57a-43ba-97f8-abb867249ad7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='login-form']/div/div[2]/div[2]/button</value>
      <webElementGuid>1a164225-97ad-4fd5-bbd2-13dfb706d315</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='*'])[4]/following::button[1]</value>
      <webElementGuid>d770b840-18d2-4c60-a2e7-e920e2ca1dbe</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='đây'])[1]/preceding::button[1]</value>
      <webElementGuid>3be6b5c9-edf8-4454-a4c3-d81cf55cf243</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/button</value>
      <webElementGuid>383de1db-14a7-4e4a-828d-ae466cdb496a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and @id = 'btn_login' and (text() = 'Đăng nhập
                            ' or . = 'Đăng nhập
                            ')]</value>
      <webElementGuid>65db63bf-9b7e-4d4c-ad5f-008a7f352c87</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
