<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_ng xut</name>
   <tag></tag>
   <elementGuidId>7234e1ad-7142-4a50-8db6-ca43de9e2e64</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link-logout</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='link-logout']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>55f41c96-563b-44cf-b0b8-82a2c12639fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://web-ecommerce.online/logout</value>
      <webElementGuid>121014f7-01f2-4ef9-b93b-fe2ceecfb419</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-logout</value>
      <webElementGuid>fc36b102-0ba9-4d42-9420-d8288f7b78ee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Đăng xuất</value>
      <webElementGuid>a4fb18de-fe7b-4aff-805e-99748fb50b86</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;link-logout&quot;)</value>
      <webElementGuid>4f6ee11f-341e-46b6-a469-2b1c5a5974d1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link-logout']</value>
      <webElementGuid>a1b0a324-99d2-4cb7-af2a-617471c94909</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='em-account-login-form']/div/ul/li[5]/a</value>
      <webElementGuid>793d9040-8d58-4297-b09d-a2c196b5ddbb</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:link</name>
      <type>Main</type>
      <value>//a[contains(text(),'Đăng xuất')]</value>
      <webElementGuid>b31f257c-2158-45ef-b570-c05ed9f68763</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Đổi mật khẩu'])[1]/following::a[1]</value>
      <webElementGuid>a37ad562-2b35-4186-98b8-471262fb0577</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sản phẩm yêu thích'])[1]/following::a[2]</value>
      <webElementGuid>517bac90-a3b0-4459-a196-183360255293</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search'])[2]/preceding::a[3]</value>
      <webElementGuid>f46e235f-8f0f-4960-9e08-09bac734baa0</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Search:'])[1]/preceding::a[4]</value>
      <webElementGuid>7a03bd00-62df-4ce0-8e96-80ea5ea0ed96</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>(//a[contains(@href, 'https://web-ecommerce.online/logout')])[2]</value>
      <webElementGuid>e2cd5ff3-f076-44b2-934d-62c3530fb6c5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/ul/li[5]/a</value>
      <webElementGuid>ab1f1328-5cc5-4682-b73b-5426bc871b4d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://web-ecommerce.online/logout' and @id = 'link-logout' and (text() = ' Đăng xuất' or . = ' Đăng xuất')]</value>
      <webElementGuid>4796af4b-bd9b-4f31-b647-eacfa1785694</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
