<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>a_Search</name>
   <tag></tag>
   <elementGuidId>02582007-cb68-46c5-8e02-68f388d18626</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#link-search</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//a[@id='link-search']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>f3c1e2a9-8dd1-45a3-8a35-46f783d3c50f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>em-search-icon</value>
      <webElementGuid>1c9bff97-d160-44aa-a96a-74ecc4bdba6c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>deaedb6f-7cca-498e-8293-0d3c305a23c2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>javascript:void(0);</value>
      <webElementGuid>8604a438-8f27-4fe8-98a7-73747f6aaf6f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>link-search</value>
      <webElementGuid>7acc2df3-59f5-41e2-9f19-5d6caa875fed</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Search</value>
      <webElementGuid>4e619626-0bcb-48f4-b293-d593745765a2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[@class=&quot;no-js&quot;]/body[@class=&quot;cms-index-index&quot;]/div[@class=&quot;wrapper&quot;]/div[@class=&quot;page two-columns-left&quot;]/div[@class=&quot;em-wrapper-header&quot;]/div[@class=&quot;hidden-xs em-header-style08&quot;]/div[@class=&quot;em-header-top&quot;]/div[@class=&quot;container&quot;]/div[@class=&quot;row&quot;]/div[@class=&quot;col-sm-24&quot;]/div[2]/div[@class=&quot;em-search f-right&quot;]/div[@class=&quot;em-top-search&quot;]/div[@class=&quot;em-wrapper-js-search em-search-style01&quot;]/div[@class=&quot;em-wrapper-search em-no-category-search&quot;]/a[@id=&quot;link-search&quot;]</value>
      <webElementGuid>7abc8392-97ff-40a1-ae67-36965947cd4c</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//a[@id='link-search']</value>
      <webElementGuid>e1af5e2d-0192-47d8-9c14-3b1fca25d518</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Hotline:'])[1]/following::a[1]</value>
      <webElementGuid>3dc85574-f98b-4a82-88e7-7cc703777698</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Chức năng đặc biệt'])[1]/following::a[3]</value>
      <webElementGuid>b5758609-5c9f-4a07-a0ec-dfc07d11d5a7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Tìm kiếm'])[1]/preceding::a[1]</value>
      <webElementGuid>bcbf65aa-b2b3-4db3-91c2-dd69c1f8d4de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'javascript:void(0);')]</value>
      <webElementGuid>25ee1909-533b-4c12-baba-cc05a8995154</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div[2]/div/div/div/div/a</value>
      <webElementGuid>c226f57d-4d70-466a-b888-7e8feaff4146</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@title = 'Search' and @href = 'javascript:void(0);' and @id = 'link-search' and (text() = 'Search' or . = 'Search')]</value>
      <webElementGuid>52cbe7b1-7488-4fcd-8504-0ab19e55c647</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
