<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Tm kim_parameter</name>
   <tag></tag>
   <elementGuidId>70ee5c75-be9e-4421-a390-07c898fbce02</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id='search']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#search</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <smartLocatorCollection>
      <entry>
         <key>SMART_LOCATOR</key>
         <value>internal:attr=[placeholder=&quot;Bạn tìm kiếm sản phẩm gì? ...&quot;i]</value>
      </entry>
   </smartLocatorCollection>
   <smartLocatorEnabled>false</smartLocatorEnabled>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>3b0513f5-e1d4-4b90-8cf2-82508efdf00b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>search</value>
      <webElementGuid>a26d9f48-eae6-4531-b545-0b8c8ccd6011</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3eb96347-407e-4b16-804e-1f4b60f244b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>parameter</value>
      <webElementGuid>f9cf5dbd-6f8a-45c3-938d-0cc47edab2d2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>input-text</value>
      <webElementGuid>909c89b6-9f7c-4249-a354-c64ea0c726da</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>maxlength</name>
      <type>Main</type>
      <value>128</value>
      <webElementGuid>6703d1de-8e74-40c3-bfe1-cca253b13c9f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Bạn tìm kiếm sản phẩm gì? ...</value>
      <webElementGuid>0aaeff2f-7276-4ddc-988b-e4e9ade6cc9d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>onkeyup</name>
      <type>Main</type>
      <value>searching()</value>
      <webElementGuid>f36d1582-8528-40b1-ab7f-170c5ab06160</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;search&quot;)</value>
      <webElementGuid>9cf9e385-0282-43a4-a49e-9518cd3fdf6a</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='search']</value>
      <webElementGuid>88560dd7-5172-41b5-9d12-fef3dd2ba198</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='search_mini_form']/div/div/input</value>
      <webElementGuid>ae454426-3ed2-4e93-ba45-2987da3719af</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div/div/div/div/form/div/div/input</value>
      <webElementGuid>36755b9f-96c0-4d93-8d02-8849e16914d1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'search' and @type = 'text' and @name = 'parameter' and @placeholder = 'Bạn tìm kiếm sản phẩm gì? ...']</value>
      <webElementGuid>1dcfc7a9-28e0-461a-8ebe-a16e3652060c</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
